export const REVIEWED_PIN = [
  338363,
  {
    "drucksache": "467/26",
    "enSourceHash": "bd62bad5e30e57bc017db3ac6928402d82490c88785b92208bfdd592900fd380",
    "en": {
      "summary_simplified": "The law governing the **Federal Supervisory Authority for Air Navigation Services** will be updated to reflect the authority's current responsibilities and current European Union requirements. Anyone who fails to comply with an order from the authority in full or on time may receive a **warning fine**. The fine may be up to **30,000 euros** for individuals and up to **4 percent of annual revenue** for organizations. Objections and legal actions do not automatically suspend measures taken by the authority.",
      "summary_detail": "## What is to change\n\n* The Federal Supervisory Authority for Air Navigation Services will be expressly designated as the national supervisory authority and the competent national authority for air navigation services.\n* Its responsibilities and references to European Union requirements will be updated.\n* Supervised individuals and organizations must provide the authority with reports and records upon request.\n* Certain air navigation service organizations must permit inspections on their premises and in business facilities where necessary for supervision. Outside business hours or in a private residence, inspections without consent are permitted only to prevent imminent dangers and where there are indications of a legal violation.\n* Anyone who fails to comply with an order, fails to comply in full, or fails to comply on time may receive a warning fine. It may amount to up to **30,000 euros** for individuals and up to **4 percent of annual revenue** for organizations.\n* The warning fine must be announced in advance with a deadline. It may be imposed again and at a different amount until the order has been fully complied with.\n* Objections and legal actions against measures taken by the authority do not automatically have suspensive effect.\n\n## Background\n\nThe existing law dates from 2009. Its provisions establishing the authority are now outdated, and European legal bases and references have also changed. The warning fine is intended to implement European Union requirements on sanctions and strengthen the enforcement of orders. According to the draft, there will be no additional expenditure or obligations for citizens, businesses, or public administration."
    }
  }
]
