export const REVIEWED_PIN = [
  338347,
  {
    "drucksache": "439/26",
    "enSourceHash": "3d410c2c78d0d73fab0e538403360fddd231dd919bcd83e917403011f69b79b9",
    "en": {
      "summary_detail": "## What is to change\n\n1. Approvals for new telecommunications lines are to be simplified. For certain work, notification is to be sufficient or no approval is to be required.\n2. The Gigabit Register is to centrally consolidate information about existing networks, planned expansion, construction work, and public land.\n3. It is to become easier to fully develop fiber optic networks within buildings, and these networks are to meet uniform minimum technical standards.\n4. Access to lines and facilities in buildings must be granted on fair and equal terms if installing a second network would be economically inefficient or practically impossible. An offer must be submitted within two weeks.\n5. Under certain conditions, operators of fiber only networks must negotiate network access with other companies. Where multiple fiber optic networks are not economically viable, the Bundesnetzagentur may set conditions and enforce an agreement.\n6. When switching from copper to fiber optics, the Bundesnetzagentur may require information and a migration plan. Open network access is to preserve the choice between providers.\n7. Consumers are to receive uninterrupted fiber optic service during the transition. In exceptional cases, at least an equivalent alternative technology that can be improved in the future must be available.\n8. The Bundesnetzagentur may use and publish data more efficiently. Personal data, trade secrets, business secrets, and security interests remain protected.\n9. The Bundesnetzagentur's responsibilities, inspection rights, and sanctioning powers concerning the European roaming rules will be adjusted.\n\n## Background\n\nHigh performance digital networks are regarded as a foundation for the economy and society. According to the Federal Government, the nationwide expansion of fiber optic and mobile networks has so far been slowed by complex approval procedures, bureaucracy, and a lack of centralized information. At the same time, the switch from the copper network to the fiber optic network must be fair, transparent, and free of service gaps. The law is also intended to align German law with European requirements for gigabit networks and roaming. The annual time burden for citizens is to decrease by **91,983 hours**, the burden on businesses by **19,713,000 euros**, and the burden on public administration by around **8,384,000 euros**."
    }
  }
]
