/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ElectionRouteImport } from './routes/election'
import { Route as CandidatesSlugRouteImport } from './routes/candidates/$slug'
import { Route as DocumentsIdRouteImport } from './routes/documents/$id'
import { Route as PartiesIndexRouteImport } from './routes/parties/index'
import { Route as PartiesSlugRouteImport } from './routes/parties/$slug'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes/index'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectionRoute = ElectionRouteImport.update({
  id: '/election',
  path: '/election',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesSlugRoute = CandidatesSlugRouteImport.update({
  id: '/candidates/$slug',
  path: '/candidates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIndexRoute = PartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesSlugRoute = PartiesSlugRouteImport.update({
  id: '/parties/$slug',
  path: '/parties/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/programmes/$slug',
  path: '/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/election': typeof ElectionRoute
  '/candidates/$slug': typeof CandidatesSlugRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/parties/$slug': typeof PartiesSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/parties/': typeof PartiesIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/election': typeof ElectionRoute
  '/candidates/$slug': typeof CandidatesSlugRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/parties/$slug': typeof PartiesSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/parties': typeof PartiesIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/election': typeof ElectionRoute
  '/candidates/$slug': typeof CandidatesSlugRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/parties/$slug': typeof PartiesSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/parties/': typeof PartiesIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/election'
    | '/candidates/$slug'
    | '/documents/$id'
    | '/parties/$slug'
    | '/programmes/$slug'
    | '/parties/'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/election'
    | '/candidates/$slug'
    | '/documents/$id'
    | '/parties/$slug'
    | '/programmes/$slug'
    | '/parties'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/election'
    | '/candidates/$slug'
    | '/documents/$id'
    | '/parties/$slug'
    | '/programmes/$slug'
    | '/parties/'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ElectionRoute: typeof ElectionRoute
  CandidatesSlugRoute: typeof CandidatesSlugRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  PartiesSlugRoute: typeof PartiesSlugRoute
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
  PartiesIndexRoute: typeof PartiesIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/election': {
      id: '/election'
      path: '/election'
      fullPath: '/election'
      preLoaderRoute: typeof ElectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$slug': {
      id: '/candidates/$slug'
      path: '/candidates/$slug'
      fullPath: '/candidates/$slug'
      preLoaderRoute: typeof CandidatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/': {
      id: '/parties/'
      path: '/parties'
      fullPath: '/parties/'
      preLoaderRoute: typeof PartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$slug': {
      id: '/parties/$slug'
      path: '/parties/$slug'
      fullPath: '/parties/$slug'
      preLoaderRoute: typeof PartiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/programmes/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ElectionRoute: ElectionRoute,
  CandidatesSlugRoute: CandidatesSlugRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  PartiesSlugRoute: PartiesSlugRoute,
  ProgrammesSlugRoute: ProgrammesSlugRoute,
  PartiesIndexRoute: PartiesIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
