export const de = {
  navVotes: 'Abstimmungen',
  navMotions: 'Anträge',
  navMembers: 'Abgeordnete',
  navSpeeches: 'Reden',
  navParties: 'Fraktionen',
  searchSpeeches: 'Reden durchsuchen',
  readFullSpeech: 'Ganze Rede lesen',
  openSpeechOf: 'Rede von {name} öffnen',
  showMore: 'Mehr anzeigen',
  viewFullDebate: 'Ganze Debatte ansehen',
  collapse: 'Einklappen',
  toVote: 'Zur Abstimmung',
  debateTimeline: 'Verlauf der Debatte',
  contributionOf: 'Wortmeldung {i} von {n}',
  nextLabel: 'Nächste',
  previousLabel: 'Vorherige',
  votes: 'Abstimmungen',
  vote: 'Stimme',
  type: 'Typ',
  proposer: 'Antragsteller',
  result: 'Ergebnis',
  category: 'Kategorie',
  namedVote: 'Namentlich',
  showOfHands: 'Handzeichen',
  division: 'Hammelsprung',
  accepted: 'Angenommen',
  rejected: 'Abgelehnt',
  officialTitle: 'Offizieller Titel',
  proposalSummary: 'Zusammenfassung des Antrags',
  details: 'Details',
  speeches: 'Reden',
  relatedSpeechesForVote: 'Verwandte Reden zur Vorlage',
  noSpeechesAvailable: 'Noch keine Reden verfügbar.',
  noSpeechesFound: 'Keine Reden gefunden.',
  noSpeechesTerm: 'Keine Reden in WP21',
  searchIndexLoading: 'Suchindex wird geladen...',
  searchPreparing: 'Suche wird vorbereitet...',
  profile: 'Profil',
  history: 'Verlauf',
  attendance: 'Anwesenheit',
  loyalty: 'Linientreue',
  deviation: 'Abweichung',
  deviations: 'Abweichungen',
  noPartyLine: 'Keine Fraktionslinie',
  noVoteData: 'Keine Abstimmungsdaten',
  missed: 'verpasst',
  contribution: 'Beitrag',
  contributions: 'Beiträge',
  years: 'Jahre',
  appearance: 'Darstellung',
  themeSystem: 'System',
  themeLight: 'Hell',
  themeDark: 'Dunkel',
  language: 'Sprache',
  german: 'Deutsch',
  english: 'English',
  aboutData: 'Daten',
  sourceCode: 'Code',
  imprint: 'Impressum',
  privacy: 'Datenschutz',
  appStorePromptTitle: 'Machtblick fürs iPhone',
  appStorePromptDescription: 'Die Machtblick App ist jetzt im App Store.',
  appStorePromptAction: 'Im App Store laden',
  appStorePromptDismiss: 'Nicht jetzt',
  appStorePromptClose: 'Schließen',
  menuOpen: 'Menü öffnen',
  menuClose: 'Menü schließen',
  previousPage: 'Vorherige Seite',
  nextPage: 'Nächste Seite',
  resetFilter: 'Filter zurücksetzen',
  searchMembers: 'Abgeordnete durchsuchen',
  members: 'Abgeordnete',
  parliamentaryGroup: 'Fraktion',
  party: 'Partei',
  state: 'Bundesland',
  sex: 'Geschlecht',
  age: 'Alter',
  mandate: 'Mandat',
  people: 'Personen',
  name: 'Name',
  line: 'Linie',
  sortLabel: 'Sortieren',
  noMembersFound: 'Keine Abgeordneten gefunden',
  filteredSummary: 'Zusammenfassung der gefilterten Auswahl',
  noData: 'Keine Daten',
  sortBy: 'Sortieren nach',
  ascending: 'aufsteigend',
  descending: 'absteigend',
  cohesion: 'Geschlossenheit',
  agreement: 'Übereinstimmung',
  agreementTooltip: '{pct} bei {n} gemeinsamen Abstimmungen',
  proposals: 'Anträge',
  majorDonations: 'Großspenden',
  seats: 'Sitze',
  seatsOfTotal: '{sum} von {total} Sitzen',
  ofBundestag: 'des Bundestags',
  successRate: 'Erfolgsquote',
  allMembersOf: 'Alle {n} Abgeordneten',
  yes: 'Ja',
  no: 'Nein',
  abstain: 'Enthalten',
  abstention: 'Enthaltung',
  abstainShort: 'Enth.',
  absentShort: 'Abw.',
  officialDataNotice: 'Alle Zahlen auf dieser Seite basieren auf den offiziellen Daten des Deutschen Bundestages.',
  officialDataLink: 'Originaldaten ansehen',
  stanceLabels: { yes: 'Dafür', no: 'Dagegen', abstain: 'Enthalten', split: 'Gespalten' },
  filterLabel: 'Filter',
  all: 'Alle',
  saved: 'Gespeichert',
  seen: 'Gesehen',
  unseen: 'Ungesehen',
  saveVote: 'Abstimmung speichern',
  unsaveVote: 'Aus gespeicherten Abstimmungen entfernen',
  markSeen: 'Als gesehen markieren',
  markUnseen: 'Als ungesehen markieren',
  absentLabel: 'abwesend',
  noDataLabel: 'ohne Daten',
  absent: 'Nicht abgegeben',
  split: 'Geteilt',
  close: 'Schließen',
  other: 'Sonstige',
  current: 'Aktuell',
  of: 'von',
  termShort: 'WP',
  founded: 'Gegründet',
  sinceToday: 'heute',
  shareOfBundestag: 'Anteil am Bundestag',
  shareOfBundestagByTerm: 'Sitzanteil je Wahlperiode',
  noDefectors: 'Keine Abweichler.',
  aiSummaryNotice: 'Diese Zusammenfassung basiert auf dem Antragstext, wurde KI-generiert und sprachlich vereinfacht.',
  fullMotion: 'Den vollständigen Antrag findest du in',
  sourcePdf: 'der Original-Drucksache (PDF)',
  noSimplifiedSummary: 'Noch keine vereinfachte Beschreibung verfügbar.',
  partySummaries: 'Debatte im Überblick',
  stampClose: {
    angenommen: 'Angenommen',
    abgelehnt: 'Abgelehnt',
    knapp: 'Knapp',
    einstimmig: 'Einstimmig',
    'fast-einstimmig': 'Fast einstimmig',
    abweichler: 'Abweichler',
    beantwortet: 'Beantwortet',
    offen: 'Offen',
    ueberwiesen: 'Überwiesen',
    beschlussempfehlung: 'Beschlussempfehlung',
    'nicht-beraten': 'Nicht beraten',
  },
  motionStatus: {
    Abgelehnt: 'Abgelehnt',
    Angenommen: 'Angenommen',
    Verkündet: 'Verkündet',
    Verabschiedet: 'Verabschiedet',
    Abgeschlossen: 'Abgeschlossen',
    'Den Ausschüssen zugewiesen': 'Den Ausschüssen zugewiesen',
    '1. Durchgang im Bundesrat abgeschlossen': '1. Durchgang im Bundesrat abgeschlossen',
    'Für erledigt erklärt': 'Für erledigt erklärt',
    'Bundesrat hat zugestimmt': 'Bundesrat hat zugestimmt',
    'Bundesrat hat Zustimmung versagt': 'Bundesrat hat Zustimmung versagt',
    'Bundesrat hat Vermittlungsausschuss nicht angerufen': 'Bundesrat hat Vermittlungsausschuss nicht angerufen',
    'Im Vermittlungsverfahren': 'Im Vermittlungsverfahren',
    'Einbringung beschlossen': 'Einbringung beschlossen',
    'Einbringung abgelehnt': 'Einbringung abgelehnt',
  } as Record<string, string>,
  ageLabels: {
    'unter-30': 'Unter 30',
    '30-39': '30 bis 39',
    '40-49': '40 bis 49',
    '50-59': '50 bis 59',
    '60-69': '60 bis 69',
    '70-plus': '70 und älter',
  },
  sexLabels: { m: 'Männlich', f: 'Weiblich', d: 'Divers', unbekannt: 'Unbekannt' },
  mandateLabels: { direkt: 'Direktmandat', liste: 'Landesliste' },
  partyHistoryEmpty: 'sitzt erst seit der {term}. Wahlperiode im Bundestag.',
  partyHistorySoon: 'Ein Verlauf wird sichtbar, sobald mindestens zwei Wahlperioden erfasst sind.',
  acceptedCount: 'angenommen',
  currentSeats: 'Sitzen',
  electoralTerm: 'Wahlperiode',
  nameAtTime: 'Name damals',
  share: 'Anteil',
  broughtBy: 'Eingebracht von',
  bill: 'Gesetzentwurf',
  motion: 'Antrag',
  motionsCount: 'Anträge',
  photo: 'Foto',
  government: 'Regierung',
  opposition: 'Opposition',
  laenderMotion: 'Antrag der Länder',
  laender: 'Länder',
  status: 'Status',
  procedure: 'Verfahren',
  stageIntroduced: 'Eingebracht',
  stageCommittee: 'Ausschuss',
  stageVote: 'Abstimmung',
  stageEnacted: 'Verkündet',
  motionBuckets: {
    angenommen: 'Angenommen',
    abgelehnt: 'Abgelehnt',
    'im-verfahren': 'Im Verfahren',
    'nicht-beraten': 'Nicht beraten',
  },
  motionsIndexCount: 'Anträge und Gesetzentwürfe',
  dipSource: 'Quelle: Dokumentations- und Informationssystem des Deutschen Bundestages',
} as const
