export const en = {
  navVotes: 'Votes',
  navMotions: 'Motions',
  navMembers: 'Members',
  navSpeeches: 'Speeches',
  navParties: 'Parties',
  searchSpeeches: 'Search speeches',
  readFullSpeech: 'Read full speech',
  openSpeechOf: 'Open speech by {name}',
  showMore: 'Show more',
  viewFullDebate: 'View full debate',
  collapse: 'Collapse',
  toVote: 'On the vote',
  debateTimeline: 'Debate timeline',
  contributionOf: 'Contribution {i} of {n}',
  nextLabel: 'Next',
  previousLabel: 'Previous',
  votes: 'Votes',
  vote: 'Vote',
  linkedVote: 'Linked vote',
  type: 'Type',
  proposer: 'Sponsor',
  result: 'Result',
  category: 'Category',
  namedVote: 'Recorded',
  showOfHands: 'Hands',
  division: 'Division',
  accepted: 'Accepted',
  rejected: 'Rejected',
  motionPdf: 'Motion as PDF',
  billPdf: 'Bill as PDF',
  officialTitle: 'Official title',
  proposalSummary: 'Proposal summary',
  details: 'Details',
  speeches: 'Speeches',
  relatedSpeechesForVote: 'Related speeches on this item',
  noSpeechesAvailable: 'No speeches available yet.',
  noSpeechesFound: 'No speeches found.',
  noSpeechesTerm: 'No speeches in term 21',
  searchIndexLoading: 'Loading search index...',
  searchPreparing: 'Preparing search...',
  profile: 'Profile',
  history: 'History',
  attendance: 'Attendance',
  loyalty: 'Party line',
  deviation: 'Deviation',
  deviations: 'Deviations',
  noPartyLine: 'No party line',
  noVoteData: 'No voting data',
  missed: 'missed',
  contribution: 'contribution',
  contributions: 'contributions',
  years: 'years old',
  appearance: 'Appearance',
  themeLight: 'Light',
  themeDark: 'Dark',
  language: 'Language',
  german: 'Deutsch',
  english: 'English',
  aboutData: 'Data',
  sourceCode: 'Code',
  imprint: 'Imprint',
  privacy: 'Privacy',
  appStoreLink: 'iPhone app',
  appStorePromptTitle: 'Machtblick for iPhone',
  appStorePromptDescription: 'The Machtblick app is now on the App Store.',
  appStorePromptAction: 'Get it on the App Store',
  appStorePromptDismiss: 'Not now',
  appStorePromptClose: 'Close',
  menuOpen: 'Open menu',
  menuClose: 'Close menu',
  previousPage: 'Previous page',
  nextPage: 'Next page',
  resetFilter: 'Reset filter',
  searchMembers: 'Search members',
  members: 'Members',
  parliamentaryGroup: 'Party',
  party: 'Party',
  state: 'State',
  sex: 'Gender',
  age: 'Age',
  mandate: 'Mandate',
  people: 'people',
  name: 'Name',
  line: 'Line',
  sortLabel: 'Sort',
  noMembersFound: 'No members found',
  filteredSummary: 'Summary of the filtered selection',
  noData: 'No data',
  sortBy: 'Sort by',
  ascending: 'ascending',
  descending: 'descending',
  cohesion: 'Cohesion',
  agreement: 'Agreement',
  agreementTooltip: '{pct} across {n} shared votes',
  proposals: 'Motions',
  majorDonations: 'Major donations',
  seats: 'seats',
  seatsOfTotal: '{sum} of {total} seats',
  ofBundestag: 'of the Bundestag',
  successRate: 'Success rate',
  allMembersOf: 'All {n} members',
  yes: 'Yes',
  no: 'No',
  abstain: 'Abstained',
  abstention: 'Abstention',
  abstainShort: 'Abst.',
  absentShort: 'Abs.',
  officialDataNoticePrefix: 'All figures on this page are based on the',
  officialDataNoticeLink: 'official data of the German Bundestag',
  stanceLabels: { yes: 'In favor', no: 'Against', abstain: 'Abstained', split: 'Split' },
  filterLabel: 'Filter',
  all: 'All',
  saved: 'Saved',
  seen: 'Seen',
  unseen: 'Unseen',
  saveVote: 'Save vote',
  unsaveVote: 'Remove from saved votes',
  markSeen: 'Mark as seen',
  markUnseen: 'Mark as unseen',
  absentLabel: 'absent',
  noDataLabel: 'no data',
  absent: 'Not cast',
  split: 'Split',
  close: 'Close',
  other: 'Other',
  current: 'Current',
  of: 'of',
  termShort: 'term',
  founded: 'Founded',
  sinceToday: 'today',
  shareOfBundestag: 'Share of the Bundestag',
  shareOfBundestagByTerm: 'Seat share by parliamentary term',
  noDefectors: 'No defectors.',
  aiSummaryNotice: 'This summary is based on the motion text. It was generated with AI and simplified linguistically.',
  fullMotion: 'The full motion is available in',
  sourcePdf: 'the source document (PDF)',
  noSimplifiedSummary: 'No simplified description is available yet.',
  partySummaries: 'Debate at a glance',
  stampClose: {
    angenommen: 'Accepted',
    abgelehnt: 'Rejected',
    knapp: 'Close',
    einstimmig: 'Unanimous',
    'fast-einstimmig': 'Almost unanimous',
    abweichler: 'Defectors',
    beantwortet: 'Answered',
    offen: 'Open',
    ueberwiesen: 'Referred',
    beschlussempfehlung: 'Recommendation',
    'im-verfahren': 'In progress',
    'nicht-beraten': 'Not debated',
  },
  motionStatus: {
    Abgelehnt: 'Rejected',
    Angenommen: 'Accepted',
    Verkündet: 'Enacted',
    Verabschiedet: 'Passed',
    Abgeschlossen: 'Concluded',
    'Den Ausschüssen zugewiesen': 'Referred to committees',
    '1. Durchgang im Bundesrat abgeschlossen': 'First Bundesrat reading completed',
    'Für erledigt erklärt': 'Declared settled',
    'Bundesrat hat zugestimmt': 'Approved by the Bundesrat',
    'Bundesrat hat Zustimmung versagt': 'Bundesrat withheld consent',
    'Bundesrat hat Vermittlungsausschuss nicht angerufen': 'Bundesrat did not call the Mediation Committee',
    'Im Vermittlungsverfahren': 'In mediation proceedings',
    'Einbringung beschlossen': 'Introduction approved',
    'Einbringung abgelehnt': 'Introduction rejected',
  } as Record<string, string>,
  ageLabels: {
    'unter-30': 'Under 30',
    '30-39': '30 to 39',
    '40-49': '40 to 49',
    '50-59': '50 to 59',
    '60-69': '60 to 69',
    '70-plus': '70 and older',
  },
  sexLabels: { m: 'Male', f: 'Female', d: 'Diverse', unbekannt: 'Unknown' },
  mandateLabels: { direkt: 'Direct mandate', liste: 'State list' },
  partyHistoryEmpty: 'has only been in the Bundestag since the {term}. electoral term.',
  partyHistorySoon: 'A timeline will appear once at least two electoral terms are recorded.',
  acceptedCount: 'accepted',
  currentSeats: 'seats',
  electoralTerm: 'electoral term',
  nameAtTime: 'Name at the time',
  share: 'Share',
  broughtBy: 'Sponsored by',
  bill: 'Bill',
  motion: 'Motion',
  motionsCount: 'Motions',
  photo: 'Photo',
  government: 'Government',
  opposition: 'Opposition',
  laenderMotion: 'Motion of the states',
  laender: 'States',
  status: 'Status',
  procedure: 'Procedure',
  stageIntroduced: 'Introduced',
  stageCommittee: 'Committee',
  stageVote: 'Vote',
  stageEnacted: 'Enacted',
  motionBuckets: {
    angenommen: 'Accepted',
    abgelehnt: 'Rejected',
    'im-verfahren': 'In progress',
    'nicht-beraten': 'Not debated',
  },
  motionsIndexCount: 'Motions and bills',
  dipSource: 'Source: Documentation system of the German Bundestag',
} as const
