enum Copy {
    static let votesTab = "Abstimmungen"
    static let membersTab = "Abgeordnete"
    static let partiesTab = "Fraktionen"
    static let moreTab = "Mehr"

    static let yes = "Ja"
    static let no = "Nein"
    static let abstain = "Enthalten"
    static let absent = "Abwesend"
    static let accepted = "Angenommen"
    static let rejected = "Abgelehnt"
    static let positionYes = "Dafür"
    static let positionNo = "Dagegen"
    static let positionAbstain = "Enthalten"
    static let positionMixed = "Gespalten"

    static let unknown = "Unbekannt"
    static let government = "Bundesregierung"
    static let resultSection = "Ergebnis"
    static let summarySection = "Zusammenfassung"
    static let debateSection = "Debatte"
    static let partiesSection = "Fraktionen"
    static let defectorsSection = "Abweichler"
    static let documentsSection = "Dokumente"
    static let sourceLink = "Quelle: bundestag.de"
    static let motionPdf = "Antrag als PDF"
    static let majority = "Mehrheit"

    static let searchMembers = "Name suchen"
    static let allParties = "Alle Fraktionen"
    static let allStates = "Alle Länder"
    static let attendance = "Anwesenheit"
    static let loyalty = "Linientreue"
    static let line = "Linie"
    static let defections = "Abweichungen"
    static let votesSection = "Abstimmungen"
    static let speechesSection = "Reden"
    static let direct = "Direktmandat"
    static let list = "Liste"
    static let constituency = "Wahlkreis"
    static let born = "Jahrgang"

    static let seats = "Sitze"
    static let cohesion = "Geschlossenheit"
    static let donationsSection = "Großspenden"
    static let donationsTotal = "Gesamt"
    static let alignmentsSection = "Übereinstimmung"
    static let membersCount = "Abgeordnete"

    static let motionTitle = "Antrag"
    static let billTitle = "Gesetzentwurf"
    static let statusLabel = "Stand"
    static let introducedLabel = "Eingebracht"
    static let signatoriesSection = "Unterzeichnende"
    static let linkedVotesSection = "Abstimmungen dazu"
    static let drucksacheLabel = "Drucksache"
    static let dipSource = "Quelle: dip.bundestag.de"

    static let aboutSection = "Über Machtblick"
    static let aboutText =
        "Machtblick macht das Abstimmungsverhalten des Deutschen Bundestags sichtbar: namentliche Abstimmungen, Abgeordnete, Fraktionen und Anträge, aufbereitet aus öffentlichen Datenquellen."
    static let dataSection = "Datenquellen"
    static let website = "machtblick.de"
    static let methodology = "Methodik"
    static let imprint = "Impressum"
    static let privacy = "Datenschutz"
    static let fontLicense = "Schrift: Fraunces (SIL Open Font License)"
    static let refreshSection = "Daten"
    static let lastRefresh = "Zuletzt aktualisiert"
    static let clearCache = "Cache leeren"
    static let never = "Nie"
    static let aiNotice = "Zusammenfassungen werden automatisiert erstellt und können Fehler enthalten."

    static let tabResult = "Ergebnis"
    static let tabDetails = "Details"
    static let tabSpeeches = "Reden"
    static let officialTitle = "Amtlicher Titel"
    static let officialDataNotice = "Alle Zahlen stammen aus den amtlichen Daten des Bundestags."
    static let officialDataLink = "Originaldaten ansehen"
    static let aiSummaryNotice =
        "Diese Zusammenfassung wurde automatisiert erstellt und kann Fehler enthalten."
    static let fullMotion = "Vollständiger Antrag"
    static let sourcePdf = "Quelle (PDF)"
    static let noDetailSummary = "Keine ausführliche Zusammenfassung verfügbar."
    static let invertedNotice =
        "Wir haben das Vorzeichen dieser Abstimmung umgedreht, damit das Ergebnis klar lesbar ist. Im Original ging es um die Ablehnung dieses Antrags. Wir zeigen das Ergebnis so, als wäre direkt über den Antrag abgestimmt worden."
    static let petitionNotice =
        "Diese Abstimmung bündelt mehrere Petitionen in einer Sammelübersicht. Das Plenum stimmt über alle enthaltenen Empfehlungen des Petitionsausschusses gemeinsam ab. Ein angenommen bedeutet, dass die Empfehlungen so beschlossen wurden, die einzelnen Petitionen können dabei sehr unterschiedlich behandelt worden sein."

    static let partySummariesTitle = "Fraktionen im Überblick"
    static let debateTimeline = "Verlauf der Debatte"
    static let readSummary = "Zusammenfassung lesen"
    static let readFullSpeech = "Ganze Rede lesen"
    static let searchSpeeches = "Reden durchsuchen"
    static let noSpeechesFound = "Keine Reden gefunden."
    static let zwischenfrage = "Zwischenfrage"
    static let viewAsConversation = "Als Unterhaltung ansehen"
    static let conversation = "Unterhaltung"
    static let showMore = "Mehr anzeigen"
    static let close = "Schließen"
    static let previousLabel = "Zurück"
    static let nextLabel = "Weiter"
    static let groupsLabel = "Fraktionen"

    static let filterLabel = "Filter"
    static let filterType = "Art"
    static let filterProposer = "Antragsteller"
    static let filterCategory = "Kategorie"
    static let namedVote = "Namentlich"
    static let showOfHands = "Handzeichen"
    static let noResults = "Keine Treffer"
    static let loadError = "Daten konnten nicht geladen werden."
    static let retry = "Erneut versuchen"
    static let filterAll = "Alle"
    static let relatedMotions = "Zugehörige Anträge"

    static let filterFaction = "Fraktion"
    static let filterState = "Bundesland"
    static let filterSex = "Geschlecht"
    static let filterAge = "Alter"
    static let filterMandate = "Mandat"
    static let sexMale = "Männlich"
    static let sexFemale = "Weiblich"
    static let sexDivers = "Divers"
    static let mandateDirekt = "Direktmandat"
    static let mandateListe = "Landesliste"
    static let ageUnder30 = "Unter 30"
    static let age30 = "30 bis 39"
    static let age40 = "40 bis 49"
    static let age50 = "50 bis 59"
    static let age60 = "60 bis 69"
    static let age70 = "70 und älter"
    static let people = "Personen"
    static let sortLabel = "Sortieren"
    static let sortName = "Name"
    static let ascending = "Aufsteigend"
    static let descending = "Absteigend"
    static let noMembersFound = "Keine Abgeordneten gefunden"
    static let demographicsFaction = "Fraktion"
    static let noData = "Keine Daten"
    static let vonWord = "von"
    static let beiWord = "bei"

    static let missed = "verpasst"
    static let years = "Jahre"
    static let noVoteData = "Keine Abstimmungsdaten"
    static let noPartyLine = "Keine Fraktionslinie"
    static let photoLabel = "Foto"
    static let successRateLabel = "Erfolgsquote"
    static let tabMotions = "Anträge"
    static let filterLine = "Linie"
    static let filterVote = "Stimme"
    static let notCast = "Nicht abgegeben"
    static let deviatedFromLine = "Abweichend von Linie"
    static let contribution = "Beitrag"
    static let contributions = "Beiträge"
    static let shortSuffix = "kurz"
    static let searchMotions = "Anträge durchsuchen"
    static let signatoriesSuffix = "Unterzeichner"
    static let noMotionsWP21 = "Keine Anträge in WP21"
    static let noMatchingMotions = "Keine passenden Anträge"

    static let govLabel = "Regierung"
    static let oppositionLabel = "Opposition"
    static let seatsGenitive = "Sitzen"
    static let fraktionslosLabel = "Fraktionslos"
    static let ofBundestag = "des Bundestags"
    static let acceptedCountSuffix = "angenommen"
    static let resultsMatchedSuffix = "Ergebnissen entsprachen der Linie der Fraktion"
    static let partyLineLabel = "Fraktionslinie"
    static let partyVotedLabel = "Fraktion stimmte"
    static let sharedVotesSuffix = "gemeinsamen Abstimmungen"
    static let tabProfile = "Profil"
    static let tabHistory = "Verlauf"
    static let shareOfBundestag = "Anteil am Bundestag"
    static let sinceToday = "heute"

    static let verfahren = "Verfahren"
    static let stageCommittee = "Ausschuss"
    static let stageVote = "Abstimmung"
    static let stageEnacted = "Verkündet"
    static let laenderMotion = "Antrag der Länder"
    static let broughtBy = "Eingebracht von"
    static let proposalSummary = "Zusammenfassung des Antrags"
    static let officialTitleMotion = "Offizieller Titel"
    static let stampUeberwiesen = "Überwiesen"
    static let stampBeschlussempfehlung = "Beschlussempfehlung"
    static let stampNichtBeraten = "Nicht beraten"
}
