enum Copy {
    static let votesTab = "Abstimmungen"
    static let membersTab = "Abgeordnete"
    static let partiesTab = "Fraktionen"
    static let moreTab = "Mehr"

    static let yes = "Ja"
    static let no = "Nein"
    static let abstain = "Enthalten"
    static let absent = "Abwesend"
    static let accepted = "Angenommen"
    static let rejected = "Abgelehnt"
    static let positionYes = "Dafür"
    static let positionNo = "Dagegen"
    static let positionAbstain = "Enthalten"
    static let positionMixed = "Gespalten"

    static let unknown = "Unbekannt"
    static let government = "Bundesregierung"
    static let resultSection = "Ergebnis"
    static let summarySection = "Zusammenfassung"
    static let debateSection = "Debatte"
    static let partiesSection = "Fraktionen"
    static let defectorsSection = "Abweichler"
    static let documentsSection = "Dokumente"
    static let sourceLink = "Quelle: bundestag.de"
    static let motionPdf = "Antrag als PDF"
    static let majority = "Mehrheit"

    static let searchMembers = "Name suchen"
    static let allParties = "Alle Fraktionen"
    static let allStates = "Alle Länder"
    static let attendance = "Anwesenheit"
    static let loyalty = "Linientreue"
    static let defections = "Abweichungen"
    static let votesSection = "Abstimmungen"
    static let speechesSection = "Reden"
    static let direct = "Direktmandat"
    static let list = "Liste"
    static let constituency = "Wahlkreis"
    static let born = "Jahrgang"

    static let seats = "Sitze"
    static let cohesion = "Geschlossenheit"
    static let donationsSection = "Großspenden"
    static let donationsTotal = "Gesamt"
    static let alignmentsSection = "Übereinstimmung"
    static let membersCount = "Abgeordnete"

    static let motionTitle = "Antrag"
    static let billTitle = "Gesetzentwurf"
    static let statusLabel = "Stand"
    static let introducedLabel = "Eingebracht"
    static let signatoriesSection = "Unterzeichnende"
    static let linkedVotesSection = "Abstimmungen dazu"
    static let drucksacheLabel = "Drucksache"
    static let dipSource = "Quelle: dip.bundestag.de"

    static let aboutSection = "Über Machtblick"
    static let aboutText =
        "Machtblick macht das Abstimmungsverhalten des Deutschen Bundestags sichtbar: namentliche Abstimmungen, Abgeordnete, Fraktionen und Anträge, aufbereitet aus öffentlichen Datenquellen."
    static let dataSection = "Datenquellen"
    static let website = "machtblick.de"
    static let methodology = "Methodik"
    static let imprint = "Impressum"
    static let privacy = "Datenschutz"
    static let fontLicense = "Schrift: Fraunces (SIL Open Font License)"
    static let refreshSection = "Daten"
    static let lastRefresh = "Zuletzt aktualisiert"
    static let clearCache = "Cache leeren"
    static let never = "Nie"
    static let aiNotice = "Zusammenfassungen werden automatisiert erstellt und können Fehler enthalten."

    static let tabResult = "Ergebnis"
    static let tabDetails = "Details"
    static let tabSpeeches = "Reden"
    static let officialTitle = "Amtlicher Titel"
    static let officialDataNotice = "Alle Zahlen stammen aus den amtlichen Daten des Bundestags."
    static let officialDataLink = "Originaldaten ansehen"
    static let aiSummaryNotice =
        "Diese Zusammenfassung wurde automatisiert erstellt und kann Fehler enthalten."
    static let fullMotion = "Vollständiger Antrag"
    static let sourcePdf = "Quelle (PDF)"
    static let noDetailSummary = "Keine ausführliche Zusammenfassung verfügbar."
    static let invertedNotice =
        "Wir haben das Vorzeichen dieser Abstimmung umgedreht, damit das Ergebnis klar lesbar ist. Im Original ging es um die Ablehnung dieses Antrags. Wir zeigen das Ergebnis so, als wäre direkt über den Antrag abgestimmt worden."
    static let petitionNotice =
        "Diese Abstimmung bündelt mehrere Petitionen in einer Sammelübersicht. Das Plenum stimmt über alle enthaltenen Empfehlungen des Petitionsausschusses gemeinsam ab. Ein angenommen bedeutet, dass die Empfehlungen so beschlossen wurden, die einzelnen Petitionen können dabei sehr unterschiedlich behandelt worden sein."

    static let partySummariesTitle = "Fraktionen im Überblick"
    static let debateTimeline = "Verlauf der Debatte"
    static let readSummary = "Zusammenfassung lesen"
    static let readFullSpeech = "Ganze Rede lesen"
    static let searchSpeeches = "Reden durchsuchen"
    static let noSpeechesFound = "Keine Reden gefunden."
    static let zwischenfrage = "Zwischenfrage"
    static let close = "Schließen"
    static let previousLabel = "Zurück"
    static let nextLabel = "Weiter"
    static let groupsLabel = "Fraktionen"

    static let filterLabel = "Filter"
    static let filterType = "Art"
    static let filterProposer = "Antragsteller"
    static let filterCategory = "Kategorie"
    static let namedVote = "Namentlich"
    static let showOfHands = "Handzeichen"
    static let noResults = "Keine Treffer"
    static let filterAll = "Alle"
    static let relatedMotions = "Zugehörige Anträge"
}
