enum Copy {
    static let votesTab = "Abstimmungen"
    static let membersTab = "Abgeordnete"
    static let partiesTab = "Fraktionen"
    static let moreTab = "Mehr"

    static let yes = "Ja"
    static let no = "Nein"
    static let abstain = "Enthalten"
    static let absent = "Abwesend"
    static let accepted = "Angenommen"
    static let rejected = "Abgelehnt"
    static let positionYes = "Dafür"
    static let positionNo = "Dagegen"
    static let positionAbstain = "Enthalten"
    static let positionMixed = "Gespalten"

    static let unknown = "Unbekannt"
    static let government = "Bundesregierung"
    static let resultSection = "Ergebnis"
    static let summarySection = "Zusammenfassung"
    static let debateSection = "Debatte"
    static let partiesSection = "Fraktionen"
    static let defectorsSection = "Abweichler"
    static let documentsSection = "Dokumente"
    static let sourceLink = "Quelle: bundestag.de"
    static let motionPdf = "Antrag als PDF"
    static let majority = "Mehrheit"

    static let searchMembers = "Name suchen"
    static let allParties = "Alle Fraktionen"
    static let allStates = "Alle Länder"
    static let attendance = "Anwesenheit"
    static let loyalty = "Linientreue"
    static let defections = "Abweichungen"
    static let votesSection = "Abstimmungen"
    static let speechesSection = "Reden"
    static let direct = "Direktmandat"
    static let list = "Liste"
    static let constituency = "Wahlkreis"
    static let born = "Jahrgang"

    static let seats = "Sitze"
    static let cohesion = "Geschlossenheit"
    static let donationsSection = "Großspenden"
    static let donationsTotal = "Gesamt"
    static let alignmentsSection = "Übereinstimmung"
    static let membersCount = "Abgeordnete"

    static let motionTitle = "Antrag"
    static let billTitle = "Gesetzentwurf"
    static let statusLabel = "Stand"
    static let introducedLabel = "Eingebracht"
    static let signatoriesSection = "Unterzeichnende"
    static let linkedVotesSection = "Abstimmungen dazu"
    static let drucksacheLabel = "Drucksache"
    static let dipSource = "Quelle: dip.bundestag.de"

    static let aboutSection = "Über Machtblick"
    static let aboutText =
        "Machtblick macht das Abstimmungsverhalten des Deutschen Bundestags sichtbar: namentliche Abstimmungen, Abgeordnete, Fraktionen und Anträge, aufbereitet aus öffentlichen Datenquellen."
    static let dataSection = "Datenquellen"
    static let website = "machtblick.de"
    static let methodology = "Methodik"
    static let imprint = "Impressum"
    static let privacy = "Datenschutz"
    static let fontLicense = "Schrift: Fraunces (SIL Open Font License)"
    static let refreshSection = "Daten"
    static let lastRefresh = "Zuletzt aktualisiert"
    static let clearCache = "Cache leeren"
    static let never = "Nie"
    static let aiNotice = "Zusammenfassungen werden automatisiert erstellt und können Fehler enthalten."
}
