/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotesIndexRouteImport } from './routes/votes/index'
import { Route as SpeechesIndexRouteImport } from './routes/speeches/index'
import { Route as PartiesIndexRouteImport } from './routes/parties/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as VotesIdRouteImport } from './routes/votes/$id'
import { Route as MotionsIdRouteImport } from './routes/motions/$id'
import { Route as EnPrivacyRouteImport } from './routes/en/privacy'
import { Route as EnImprintRouteImport } from './routes/en/imprint'
import { Route as PartiesIdRouteRouteImport } from './routes/parties/$id/route'
import { Route as MembersIdRouteRouteImport } from './routes/members/$id/route'
import { Route as PartiesIdIndexRouteImport } from './routes/parties/$id/index'
import { Route as MembersIdIndexRouteImport } from './routes/members/$id/index'
import { Route as EnVotesIndexRouteImport } from './routes/en/votes/index'
import { Route as EnSpeechesIndexRouteImport } from './routes/en/speeches/index'
import { Route as EnPartiesIndexRouteImport } from './routes/en/parties/index'
import { Route as EnMembersIndexRouteImport } from './routes/en/members/index'
import { Route as PartiesIdVotesRouteImport } from './routes/parties/$id/votes'
import { Route as PartiesIdProfileRouteImport } from './routes/parties/$id/profile'
import { Route as PartiesIdHistoryRouteImport } from './routes/parties/$id/history'
import { Route as MembersIdVotesRouteImport } from './routes/members/$id/votes'
import { Route as MembersIdSpeechesRouteImport } from './routes/members/$id/speeches'
import { Route as MembersIdMotionsRouteImport } from './routes/members/$id/motions'
import { Route as EnVotesIdRouteImport } from './routes/en/votes/$id'
import { Route as EnMotionsIdRouteImport } from './routes/en/motions/$id'
import { Route as EnPartiesIdRouteRouteImport } from './routes/en/parties/$id/route'
import { Route as EnMembersIdRouteRouteImport } from './routes/en/members/$id/route'
import { Route as EnPartiesIdIndexRouteImport } from './routes/en/parties/$id/index'
import { Route as EnMembersIdIndexRouteImport } from './routes/en/members/$id/index'
import { Route as EnPartiesIdVotesRouteImport } from './routes/en/parties/$id/votes'
import { Route as EnPartiesIdProfileRouteImport } from './routes/en/parties/$id/profile'
import { Route as EnPartiesIdHistoryRouteImport } from './routes/en/parties/$id/history'
import { Route as EnMembersIdVotesRouteImport } from './routes/en/members/$id/votes'
import { Route as EnMembersIdSpeechesRouteImport } from './routes/en/members/$id/speeches'
import { Route as EnMembersIdMotionsRouteImport } from './routes/en/members/$id/motions'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesIndexRoute = VotesIndexRouteImport.update({
  id: '/votes/',
  path: '/votes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechesIndexRoute = SpeechesIndexRouteImport.update({
  id: '/speeches/',
  path: '/speeches/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIndexRoute = PartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesIdRoute = VotesIdRouteImport.update({
  id: '/votes/$id',
  path: '/votes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MotionsIdRoute = MotionsIdRouteImport.update({
  id: '/motions/$id',
  path: '/motions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/en/privacy',
  path: '/en/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnImprintRoute = EnImprintRouteImport.update({
  id: '/en/imprint',
  path: '/en/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRouteRoute = PartiesIdRouteRouteImport.update({
  id: '/parties/$id',
  path: '/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdRouteRoute = MembersIdRouteRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdIndexRoute = PartiesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartiesIdRouteRoute,
} as any)
const MembersIdIndexRoute = MembersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersIdRouteRoute,
} as any)
const EnVotesIndexRoute = EnVotesIndexRouteImport.update({
  id: '/en/votes/',
  path: '/en/votes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSpeechesIndexRoute = EnSpeechesIndexRouteImport.update({
  id: '/en/speeches/',
  path: '/en/speeches/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPartiesIndexRoute = EnPartiesIndexRouteImport.update({
  id: '/en/parties/',
  path: '/en/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMembersIndexRoute = EnMembersIndexRouteImport.update({
  id: '/en/members/',
  path: '/en/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdVotesRoute = PartiesIdVotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => PartiesIdRouteRoute,
} as any)
const PartiesIdProfileRoute = PartiesIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PartiesIdRouteRoute,
} as any)
const PartiesIdHistoryRoute = PartiesIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PartiesIdRouteRoute,
} as any)
const MembersIdVotesRoute = MembersIdVotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => MembersIdRouteRoute,
} as any)
const MembersIdSpeechesRoute = MembersIdSpeechesRouteImport.update({
  id: '/speeches',
  path: '/speeches',
  getParentRoute: () => MembersIdRouteRoute,
} as any)
const MembersIdMotionsRoute = MembersIdMotionsRouteImport.update({
  id: '/motions',
  path: '/motions',
  getParentRoute: () => MembersIdRouteRoute,
} as any)
const EnVotesIdRoute = EnVotesIdRouteImport.update({
  id: '/en/votes/$id',
  path: '/en/votes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMotionsIdRoute = EnMotionsIdRouteImport.update({
  id: '/en/motions/$id',
  path: '/en/motions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPartiesIdRouteRoute = EnPartiesIdRouteRouteImport.update({
  id: '/en/parties/$id',
  path: '/en/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnMembersIdRouteRoute = EnMembersIdRouteRouteImport.update({
  id: '/en/members/$id',
  path: '/en/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPartiesIdIndexRoute = EnPartiesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnPartiesIdRouteRoute,
} as any)
const EnMembersIdIndexRoute = EnMembersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnMembersIdRouteRoute,
} as any)
const EnPartiesIdVotesRoute = EnPartiesIdVotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => EnPartiesIdRouteRoute,
} as any)
const EnPartiesIdProfileRoute = EnPartiesIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EnPartiesIdRouteRoute,
} as any)
const EnPartiesIdHistoryRoute = EnPartiesIdHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => EnPartiesIdRouteRoute,
} as any)
const EnMembersIdVotesRoute = EnMembersIdVotesRouteImport.update({
  id: '/votes',
  path: '/votes',
  getParentRoute: () => EnMembersIdRouteRoute,
} as any)
const EnMembersIdSpeechesRoute = EnMembersIdSpeechesRouteImport.update({
  id: '/speeches',
  path: '/speeches',
  getParentRoute: () => EnMembersIdRouteRoute,
} as any)
const EnMembersIdMotionsRoute = EnMembersIdMotionsRouteImport.update({
  id: '/motions',
  path: '/motions',
  getParentRoute: () => EnMembersIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/members/$id': typeof MembersIdRouteRouteWithChildren
  '/parties/$id': typeof PartiesIdRouteRouteWithChildren
  '/en/imprint': typeof EnImprintRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/motions/$id': typeof MotionsIdRoute
  '/votes/$id': typeof VotesIdRoute
  '/en/': typeof EnIndexRoute
  '/members/': typeof MembersIndexRoute
  '/parties/': typeof PartiesIndexRoute
  '/speeches/': typeof SpeechesIndexRoute
  '/votes/': typeof VotesIndexRoute
  '/en/members/$id': typeof EnMembersIdRouteRouteWithChildren
  '/en/parties/$id': typeof EnPartiesIdRouteRouteWithChildren
  '/en/motions/$id': typeof EnMotionsIdRoute
  '/en/votes/$id': typeof EnVotesIdRoute
  '/members/$id/motions': typeof MembersIdMotionsRoute
  '/members/$id/speeches': typeof MembersIdSpeechesRoute
  '/members/$id/votes': typeof MembersIdVotesRoute
  '/parties/$id/history': typeof PartiesIdHistoryRoute
  '/parties/$id/profile': typeof PartiesIdProfileRoute
  '/parties/$id/votes': typeof PartiesIdVotesRoute
  '/en/members/': typeof EnMembersIndexRoute
  '/en/parties/': typeof EnPartiesIndexRoute
  '/en/speeches/': typeof EnSpeechesIndexRoute
  '/en/votes/': typeof EnVotesIndexRoute
  '/members/$id/': typeof MembersIdIndexRoute
  '/parties/$id/': typeof PartiesIdIndexRoute
  '/en/members/$id/motions': typeof EnMembersIdMotionsRoute
  '/en/members/$id/speeches': typeof EnMembersIdSpeechesRoute
  '/en/members/$id/votes': typeof EnMembersIdVotesRoute
  '/en/parties/$id/history': typeof EnPartiesIdHistoryRoute
  '/en/parties/$id/profile': typeof EnPartiesIdProfileRoute
  '/en/parties/$id/votes': typeof EnPartiesIdVotesRoute
  '/en/members/$id/': typeof EnMembersIdIndexRoute
  '/en/parties/$id/': typeof EnPartiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/en/imprint': typeof EnImprintRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/motions/$id': typeof MotionsIdRoute
  '/votes/$id': typeof VotesIdRoute
  '/en': typeof EnIndexRoute
  '/members': typeof MembersIndexRoute
  '/parties': typeof PartiesIndexRoute
  '/speeches': typeof SpeechesIndexRoute
  '/votes': typeof VotesIndexRoute
  '/en/motions/$id': typeof EnMotionsIdRoute
  '/en/votes/$id': typeof EnVotesIdRoute
  '/members/$id/motions': typeof MembersIdMotionsRoute
  '/members/$id/speeches': typeof MembersIdSpeechesRoute
  '/members/$id/votes': typeof MembersIdVotesRoute
  '/parties/$id/history': typeof PartiesIdHistoryRoute
  '/parties/$id/profile': typeof PartiesIdProfileRoute
  '/parties/$id/votes': typeof PartiesIdVotesRoute
  '/en/members': typeof EnMembersIndexRoute
  '/en/parties': typeof EnPartiesIndexRoute
  '/en/speeches': typeof EnSpeechesIndexRoute
  '/en/votes': typeof EnVotesIndexRoute
  '/members/$id': typeof MembersIdIndexRoute
  '/parties/$id': typeof PartiesIdIndexRoute
  '/en/members/$id/motions': typeof EnMembersIdMotionsRoute
  '/en/members/$id/speeches': typeof EnMembersIdSpeechesRoute
  '/en/members/$id/votes': typeof EnMembersIdVotesRoute
  '/en/parties/$id/history': typeof EnPartiesIdHistoryRoute
  '/en/parties/$id/profile': typeof EnPartiesIdProfileRoute
  '/en/parties/$id/votes': typeof EnPartiesIdVotesRoute
  '/en/members/$id': typeof EnMembersIdIndexRoute
  '/en/parties/$id': typeof EnPartiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/members/$id': typeof MembersIdRouteRouteWithChildren
  '/parties/$id': typeof PartiesIdRouteRouteWithChildren
  '/en/imprint': typeof EnImprintRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/motions/$id': typeof MotionsIdRoute
  '/votes/$id': typeof VotesIdRoute
  '/en/': typeof EnIndexRoute
  '/members/': typeof MembersIndexRoute
  '/parties/': typeof PartiesIndexRoute
  '/speeches/': typeof SpeechesIndexRoute
  '/votes/': typeof VotesIndexRoute
  '/en/members/$id': typeof EnMembersIdRouteRouteWithChildren
  '/en/parties/$id': typeof EnPartiesIdRouteRouteWithChildren
  '/en/motions/$id': typeof EnMotionsIdRoute
  '/en/votes/$id': typeof EnVotesIdRoute
  '/members/$id/motions': typeof MembersIdMotionsRoute
  '/members/$id/speeches': typeof MembersIdSpeechesRoute
  '/members/$id/votes': typeof MembersIdVotesRoute
  '/parties/$id/history': typeof PartiesIdHistoryRoute
  '/parties/$id/profile': typeof PartiesIdProfileRoute
  '/parties/$id/votes': typeof PartiesIdVotesRoute
  '/en/members/': typeof EnMembersIndexRoute
  '/en/parties/': typeof EnPartiesIndexRoute
  '/en/speeches/': typeof EnSpeechesIndexRoute
  '/en/votes/': typeof EnVotesIndexRoute
  '/members/$id/': typeof MembersIdIndexRoute
  '/parties/$id/': typeof PartiesIdIndexRoute
  '/en/members/$id/motions': typeof EnMembersIdMotionsRoute
  '/en/members/$id/speeches': typeof EnMembersIdSpeechesRoute
  '/en/members/$id/votes': typeof EnMembersIdVotesRoute
  '/en/parties/$id/history': typeof EnPartiesIdHistoryRoute
  '/en/parties/$id/profile': typeof EnPartiesIdProfileRoute
  '/en/parties/$id/votes': typeof EnPartiesIdVotesRoute
  '/en/members/$id/': typeof EnMembersIdIndexRoute
  '/en/parties/$id/': typeof EnPartiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imprint'
    | '/privacy'
    | '/members/$id'
    | '/parties/$id'
    | '/en/imprint'
    | '/en/privacy'
    | '/motions/$id'
    | '/votes/$id'
    | '/en/'
    | '/members/'
    | '/parties/'
    | '/speeches/'
    | '/votes/'
    | '/en/members/$id'
    | '/en/parties/$id'
    | '/en/motions/$id'
    | '/en/votes/$id'
    | '/members/$id/motions'
    | '/members/$id/speeches'
    | '/members/$id/votes'
    | '/parties/$id/history'
    | '/parties/$id/profile'
    | '/parties/$id/votes'
    | '/en/members/'
    | '/en/parties/'
    | '/en/speeches/'
    | '/en/votes/'
    | '/members/$id/'
    | '/parties/$id/'
    | '/en/members/$id/motions'
    | '/en/members/$id/speeches'
    | '/en/members/$id/votes'
    | '/en/parties/$id/history'
    | '/en/parties/$id/profile'
    | '/en/parties/$id/votes'
    | '/en/members/$id/'
    | '/en/parties/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imprint'
    | '/privacy'
    | '/en/imprint'
    | '/en/privacy'
    | '/motions/$id'
    | '/votes/$id'
    | '/en'
    | '/members'
    | '/parties'
    | '/speeches'
    | '/votes'
    | '/en/motions/$id'
    | '/en/votes/$id'
    | '/members/$id/motions'
    | '/members/$id/speeches'
    | '/members/$id/votes'
    | '/parties/$id/history'
    | '/parties/$id/profile'
    | '/parties/$id/votes'
    | '/en/members'
    | '/en/parties'
    | '/en/speeches'
    | '/en/votes'
    | '/members/$id'
    | '/parties/$id'
    | '/en/members/$id/motions'
    | '/en/members/$id/speeches'
    | '/en/members/$id/votes'
    | '/en/parties/$id/history'
    | '/en/parties/$id/profile'
    | '/en/parties/$id/votes'
    | '/en/members/$id'
    | '/en/parties/$id'
  id:
    | '__root__'
    | '/'
    | '/imprint'
    | '/privacy'
    | '/members/$id'
    | '/parties/$id'
    | '/en/imprint'
    | '/en/privacy'
    | '/motions/$id'
    | '/votes/$id'
    | '/en/'
    | '/members/'
    | '/parties/'
    | '/speeches/'
    | '/votes/'
    | '/en/members/$id'
    | '/en/parties/$id'
    | '/en/motions/$id'
    | '/en/votes/$id'
    | '/members/$id/motions'
    | '/members/$id/speeches'
    | '/members/$id/votes'
    | '/parties/$id/history'
    | '/parties/$id/profile'
    | '/parties/$id/votes'
    | '/en/members/'
    | '/en/parties/'
    | '/en/speeches/'
    | '/en/votes/'
    | '/members/$id/'
    | '/parties/$id/'
    | '/en/members/$id/motions'
    | '/en/members/$id/speeches'
    | '/en/members/$id/votes'
    | '/en/parties/$id/history'
    | '/en/parties/$id/profile'
    | '/en/parties/$id/votes'
    | '/en/members/$id/'
    | '/en/parties/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  MembersIdRouteRoute: typeof MembersIdRouteRouteWithChildren
  PartiesIdRouteRoute: typeof PartiesIdRouteRouteWithChildren
  EnImprintRoute: typeof EnImprintRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  MotionsIdRoute: typeof MotionsIdRoute
  VotesIdRoute: typeof VotesIdRoute
  EnIndexRoute: typeof EnIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
  PartiesIndexRoute: typeof PartiesIndexRoute
  SpeechesIndexRoute: typeof SpeechesIndexRoute
  VotesIndexRoute: typeof VotesIndexRoute
  EnMembersIdRouteRoute: typeof EnMembersIdRouteRouteWithChildren
  EnPartiesIdRouteRoute: typeof EnPartiesIdRouteRouteWithChildren
  EnMotionsIdRoute: typeof EnMotionsIdRoute
  EnVotesIdRoute: typeof EnVotesIdRoute
  EnMembersIndexRoute: typeof EnMembersIndexRoute
  EnPartiesIndexRoute: typeof EnPartiesIndexRoute
  EnSpeechesIndexRoute: typeof EnSpeechesIndexRoute
  EnVotesIndexRoute: typeof EnVotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/': {
      id: '/votes/'
      path: '/votes'
      fullPath: '/votes/'
      preLoaderRoute: typeof VotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speeches/': {
      id: '/speeches/'
      path: '/speeches'
      fullPath: '/speeches/'
      preLoaderRoute: typeof SpeechesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/': {
      id: '/parties/'
      path: '/parties'
      fullPath: '/parties/'
      preLoaderRoute: typeof PartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/$id': {
      id: '/votes/$id'
      path: '/votes/$id'
      fullPath: '/votes/$id'
      preLoaderRoute: typeof VotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motions/$id': {
      id: '/motions/$id'
      path: '/motions/$id'
      fullPath: '/motions/$id'
      preLoaderRoute: typeof MotionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/en/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/imprint': {
      id: '/en/imprint'
      path: '/en/imprint'
      fullPath: '/en/imprint'
      preLoaderRoute: typeof EnImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/parties/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id/': {
      id: '/parties/$id/'
      path: '/'
      fullPath: '/parties/$id/'
      preLoaderRoute: typeof PartiesIdIndexRouteImport
      parentRoute: typeof PartiesIdRouteRoute
    }
    '/members/$id/': {
      id: '/members/$id/'
      path: '/'
      fullPath: '/members/$id/'
      preLoaderRoute: typeof MembersIdIndexRouteImport
      parentRoute: typeof MembersIdRouteRoute
    }
    '/en/votes/': {
      id: '/en/votes/'
      path: '/en/votes'
      fullPath: '/en/votes/'
      preLoaderRoute: typeof EnVotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/speeches/': {
      id: '/en/speeches/'
      path: '/en/speeches'
      fullPath: '/en/speeches/'
      preLoaderRoute: typeof EnSpeechesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/parties/': {
      id: '/en/parties/'
      path: '/en/parties'
      fullPath: '/en/parties/'
      preLoaderRoute: typeof EnPartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/members/': {
      id: '/en/members/'
      path: '/en/members'
      fullPath: '/en/members/'
      preLoaderRoute: typeof EnMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id/votes': {
      id: '/parties/$id/votes'
      path: '/votes'
      fullPath: '/parties/$id/votes'
      preLoaderRoute: typeof PartiesIdVotesRouteImport
      parentRoute: typeof PartiesIdRouteRoute
    }
    '/parties/$id/profile': {
      id: '/parties/$id/profile'
      path: '/profile'
      fullPath: '/parties/$id/profile'
      preLoaderRoute: typeof PartiesIdProfileRouteImport
      parentRoute: typeof PartiesIdRouteRoute
    }
    '/parties/$id/history': {
      id: '/parties/$id/history'
      path: '/history'
      fullPath: '/parties/$id/history'
      preLoaderRoute: typeof PartiesIdHistoryRouteImport
      parentRoute: typeof PartiesIdRouteRoute
    }
    '/members/$id/votes': {
      id: '/members/$id/votes'
      path: '/votes'
      fullPath: '/members/$id/votes'
      preLoaderRoute: typeof MembersIdVotesRouteImport
      parentRoute: typeof MembersIdRouteRoute
    }
    '/members/$id/speeches': {
      id: '/members/$id/speeches'
      path: '/speeches'
      fullPath: '/members/$id/speeches'
      preLoaderRoute: typeof MembersIdSpeechesRouteImport
      parentRoute: typeof MembersIdRouteRoute
    }
    '/members/$id/motions': {
      id: '/members/$id/motions'
      path: '/motions'
      fullPath: '/members/$id/motions'
      preLoaderRoute: typeof MembersIdMotionsRouteImport
      parentRoute: typeof MembersIdRouteRoute
    }
    '/en/votes/$id': {
      id: '/en/votes/$id'
      path: '/en/votes/$id'
      fullPath: '/en/votes/$id'
      preLoaderRoute: typeof EnVotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/motions/$id': {
      id: '/en/motions/$id'
      path: '/en/motions/$id'
      fullPath: '/en/motions/$id'
      preLoaderRoute: typeof EnMotionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/parties/$id': {
      id: '/en/parties/$id'
      path: '/en/parties/$id'
      fullPath: '/en/parties/$id'
      preLoaderRoute: typeof EnPartiesIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/members/$id': {
      id: '/en/members/$id'
      path: '/en/members/$id'
      fullPath: '/en/members/$id'
      preLoaderRoute: typeof EnMembersIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/parties/$id/': {
      id: '/en/parties/$id/'
      path: '/'
      fullPath: '/en/parties/$id/'
      preLoaderRoute: typeof EnPartiesIdIndexRouteImport
      parentRoute: typeof EnPartiesIdRouteRoute
    }
    '/en/members/$id/': {
      id: '/en/members/$id/'
      path: '/'
      fullPath: '/en/members/$id/'
      preLoaderRoute: typeof EnMembersIdIndexRouteImport
      parentRoute: typeof EnMembersIdRouteRoute
    }
    '/en/parties/$id/votes': {
      id: '/en/parties/$id/votes'
      path: '/votes'
      fullPath: '/en/parties/$id/votes'
      preLoaderRoute: typeof EnPartiesIdVotesRouteImport
      parentRoute: typeof EnPartiesIdRouteRoute
    }
    '/en/parties/$id/profile': {
      id: '/en/parties/$id/profile'
      path: '/profile'
      fullPath: '/en/parties/$id/profile'
      preLoaderRoute: typeof EnPartiesIdProfileRouteImport
      parentRoute: typeof EnPartiesIdRouteRoute
    }
    '/en/parties/$id/history': {
      id: '/en/parties/$id/history'
      path: '/history'
      fullPath: '/en/parties/$id/history'
      preLoaderRoute: typeof EnPartiesIdHistoryRouteImport
      parentRoute: typeof EnPartiesIdRouteRoute
    }
    '/en/members/$id/votes': {
      id: '/en/members/$id/votes'
      path: '/votes'
      fullPath: '/en/members/$id/votes'
      preLoaderRoute: typeof EnMembersIdVotesRouteImport
      parentRoute: typeof EnMembersIdRouteRoute
    }
    '/en/members/$id/speeches': {
      id: '/en/members/$id/speeches'
      path: '/speeches'
      fullPath: '/en/members/$id/speeches'
      preLoaderRoute: typeof EnMembersIdSpeechesRouteImport
      parentRoute: typeof EnMembersIdRouteRoute
    }
    '/en/members/$id/motions': {
      id: '/en/members/$id/motions'
      path: '/motions'
      fullPath: '/en/members/$id/motions'
      preLoaderRoute: typeof EnMembersIdMotionsRouteImport
      parentRoute: typeof EnMembersIdRouteRoute
    }
  }
}

interface MembersIdRouteRouteChildren {
  MembersIdMotionsRoute: typeof MembersIdMotionsRoute
  MembersIdSpeechesRoute: typeof MembersIdSpeechesRoute
  MembersIdVotesRoute: typeof MembersIdVotesRoute
  MembersIdIndexRoute: typeof MembersIdIndexRoute
}

const MembersIdRouteRouteChildren: MembersIdRouteRouteChildren = {
  MembersIdMotionsRoute: MembersIdMotionsRoute,
  MembersIdSpeechesRoute: MembersIdSpeechesRoute,
  MembersIdVotesRoute: MembersIdVotesRoute,
  MembersIdIndexRoute: MembersIdIndexRoute,
}

const MembersIdRouteRouteWithChildren = MembersIdRouteRoute._addFileChildren(
  MembersIdRouteRouteChildren,
)

interface PartiesIdRouteRouteChildren {
  PartiesIdHistoryRoute: typeof PartiesIdHistoryRoute
  PartiesIdProfileRoute: typeof PartiesIdProfileRoute
  PartiesIdVotesRoute: typeof PartiesIdVotesRoute
  PartiesIdIndexRoute: typeof PartiesIdIndexRoute
}

const PartiesIdRouteRouteChildren: PartiesIdRouteRouteChildren = {
  PartiesIdHistoryRoute: PartiesIdHistoryRoute,
  PartiesIdProfileRoute: PartiesIdProfileRoute,
  PartiesIdVotesRoute: PartiesIdVotesRoute,
  PartiesIdIndexRoute: PartiesIdIndexRoute,
}

const PartiesIdRouteRouteWithChildren = PartiesIdRouteRoute._addFileChildren(
  PartiesIdRouteRouteChildren,
)

interface EnMembersIdRouteRouteChildren {
  EnMembersIdMotionsRoute: typeof EnMembersIdMotionsRoute
  EnMembersIdSpeechesRoute: typeof EnMembersIdSpeechesRoute
  EnMembersIdVotesRoute: typeof EnMembersIdVotesRoute
  EnMembersIdIndexRoute: typeof EnMembersIdIndexRoute
}

const EnMembersIdRouteRouteChildren: EnMembersIdRouteRouteChildren = {
  EnMembersIdMotionsRoute: EnMembersIdMotionsRoute,
  EnMembersIdSpeechesRoute: EnMembersIdSpeechesRoute,
  EnMembersIdVotesRoute: EnMembersIdVotesRoute,
  EnMembersIdIndexRoute: EnMembersIdIndexRoute,
}

const EnMembersIdRouteRouteWithChildren =
  EnMembersIdRouteRoute._addFileChildren(EnMembersIdRouteRouteChildren)

interface EnPartiesIdRouteRouteChildren {
  EnPartiesIdHistoryRoute: typeof EnPartiesIdHistoryRoute
  EnPartiesIdProfileRoute: typeof EnPartiesIdProfileRoute
  EnPartiesIdVotesRoute: typeof EnPartiesIdVotesRoute
  EnPartiesIdIndexRoute: typeof EnPartiesIdIndexRoute
}

const EnPartiesIdRouteRouteChildren: EnPartiesIdRouteRouteChildren = {
  EnPartiesIdHistoryRoute: EnPartiesIdHistoryRoute,
  EnPartiesIdProfileRoute: EnPartiesIdProfileRoute,
  EnPartiesIdVotesRoute: EnPartiesIdVotesRoute,
  EnPartiesIdIndexRoute: EnPartiesIdIndexRoute,
}

const EnPartiesIdRouteRouteWithChildren =
  EnPartiesIdRouteRoute._addFileChildren(EnPartiesIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  MembersIdRouteRoute: MembersIdRouteRouteWithChildren,
  PartiesIdRouteRoute: PartiesIdRouteRouteWithChildren,
  EnImprintRoute: EnImprintRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  MotionsIdRoute: MotionsIdRoute,
  VotesIdRoute: VotesIdRoute,
  EnIndexRoute: EnIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
  PartiesIndexRoute: PartiesIndexRoute,
  SpeechesIndexRoute: SpeechesIndexRoute,
  VotesIndexRoute: VotesIndexRoute,
  EnMembersIdRouteRoute: EnMembersIdRouteRouteWithChildren,
  EnPartiesIdRouteRoute: EnPartiesIdRouteRouteWithChildren,
  EnMotionsIdRoute: EnMotionsIdRoute,
  EnVotesIdRoute: EnVotesIdRoute,
  EnMembersIndexRoute: EnMembersIndexRoute,
  EnPartiesIndexRoute: EnPartiesIndexRoute,
  EnSpeechesIndexRoute: EnSpeechesIndexRoute,
  EnVotesIndexRoute: EnVotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
