/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotesIndexRouteImport } from './routes/votes/index'
import { Route as RedenIndexRouteImport } from './routes/reden/index'
import { Route as PartiesIndexRouteImport } from './routes/parties/index'
import { Route as MembersIndexRouteImport } from './routes/members/index'
import { Route as VotesIdRouteImport } from './routes/votes/$id'
import { Route as PartiesIdRouteRouteImport } from './routes/parties/$id/route'
import { Route as MembersIdRouteRouteImport } from './routes/members/$id/route'
import { Route as PartiesIdIndexRouteImport } from './routes/parties/$id/index'
import { Route as MembersIdIndexRouteImport } from './routes/members/$id/index'
import { Route as PartiesIdVerlaufRouteImport } from './routes/parties/$id/verlauf'
import { Route as PartiesIdProfilRouteImport } from './routes/parties/$id/profil'
import { Route as PartiesIdAbstimmungenRouteImport } from './routes/parties/$id/abstimmungen'
import { Route as MembersIdRedenRouteImport } from './routes/members/$id/reden'
import { Route as MembersIdAnfragenRouteImport } from './routes/members/$id/anfragen'
import { Route as MembersIdAbstimmungenRouteImport } from './routes/members/$id/abstimmungen'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesIndexRoute = VotesIndexRouteImport.update({
  id: '/votes/',
  path: '/votes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedenIndexRoute = RedenIndexRouteImport.update({
  id: '/reden/',
  path: '/reden/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIndexRoute = PartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotesIdRoute = VotesIdRouteImport.update({
  id: '/votes/$id',
  path: '/votes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdRouteRoute = PartiesIdRouteRouteImport.update({
  id: '/parties/$id',
  path: '/parties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIdRouteRoute = MembersIdRouteRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesIdIndexRoute = PartiesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartiesIdRouteRoute,
} as any)
const MembersIdIndexRoute = MembersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersIdRouteRoute,
} as any)
const PartiesIdVerlaufRoute = PartiesIdVerlaufRouteImport.update({
  id: '/verlauf',
  path: '/verlauf',
  getParentRoute: () => PartiesIdRouteRoute,
} as any)
const PartiesIdProfilRoute = PartiesIdProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PartiesIdRouteRoute,
} as any)
const PartiesIdAbstimmungenRoute = PartiesIdAbstimmungenRouteImport.update({
  id: '/abstimmungen',
  path: '/abstimmungen',
  getParentRoute: () => PartiesIdRouteRoute,
} as any)
const MembersIdRedenRoute = MembersIdRedenRouteImport.update({
  id: '/reden',
  path: '/reden',
  getParentRoute: () => MembersIdRouteRoute,
} as any)
const MembersIdAnfragenRoute = MembersIdAnfragenRouteImport.update({
  id: '/anfragen',
  path: '/anfragen',
  getParentRoute: () => MembersIdRouteRoute,
} as any)
const MembersIdAbstimmungenRoute = MembersIdAbstimmungenRouteImport.update({
  id: '/abstimmungen',
  path: '/abstimmungen',
  getParentRoute: () => MembersIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/members/$id': typeof MembersIdRouteRouteWithChildren
  '/parties/$id': typeof PartiesIdRouteRouteWithChildren
  '/votes/$id': typeof VotesIdRoute
  '/members/': typeof MembersIndexRoute
  '/parties/': typeof PartiesIndexRoute
  '/reden/': typeof RedenIndexRoute
  '/votes/': typeof VotesIndexRoute
  '/members/$id/abstimmungen': typeof MembersIdAbstimmungenRoute
  '/members/$id/anfragen': typeof MembersIdAnfragenRoute
  '/members/$id/reden': typeof MembersIdRedenRoute
  '/parties/$id/abstimmungen': typeof PartiesIdAbstimmungenRoute
  '/parties/$id/profil': typeof PartiesIdProfilRoute
  '/parties/$id/verlauf': typeof PartiesIdVerlaufRoute
  '/members/$id/': typeof MembersIdIndexRoute
  '/parties/$id/': typeof PartiesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/votes/$id': typeof VotesIdRoute
  '/members': typeof MembersIndexRoute
  '/parties': typeof PartiesIndexRoute
  '/reden': typeof RedenIndexRoute
  '/votes': typeof VotesIndexRoute
  '/members/$id/abstimmungen': typeof MembersIdAbstimmungenRoute
  '/members/$id/anfragen': typeof MembersIdAnfragenRoute
  '/members/$id/reden': typeof MembersIdRedenRoute
  '/parties/$id/abstimmungen': typeof PartiesIdAbstimmungenRoute
  '/parties/$id/profil': typeof PartiesIdProfilRoute
  '/parties/$id/verlauf': typeof PartiesIdVerlaufRoute
  '/members/$id': typeof MembersIdIndexRoute
  '/parties/$id': typeof PartiesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/members/$id': typeof MembersIdRouteRouteWithChildren
  '/parties/$id': typeof PartiesIdRouteRouteWithChildren
  '/votes/$id': typeof VotesIdRoute
  '/members/': typeof MembersIndexRoute
  '/parties/': typeof PartiesIndexRoute
  '/reden/': typeof RedenIndexRoute
  '/votes/': typeof VotesIndexRoute
  '/members/$id/abstimmungen': typeof MembersIdAbstimmungenRoute
  '/members/$id/anfragen': typeof MembersIdAnfragenRoute
  '/members/$id/reden': typeof MembersIdRedenRoute
  '/parties/$id/abstimmungen': typeof PartiesIdAbstimmungenRoute
  '/parties/$id/profil': typeof PartiesIdProfilRoute
  '/parties/$id/verlauf': typeof PartiesIdVerlaufRoute
  '/members/$id/': typeof MembersIdIndexRoute
  '/parties/$id/': typeof PartiesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/members/$id'
    | '/parties/$id'
    | '/votes/$id'
    | '/members/'
    | '/parties/'
    | '/reden/'
    | '/votes/'
    | '/members/$id/abstimmungen'
    | '/members/$id/anfragen'
    | '/members/$id/reden'
    | '/parties/$id/abstimmungen'
    | '/parties/$id/profil'
    | '/parties/$id/verlauf'
    | '/members/$id/'
    | '/parties/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/votes/$id'
    | '/members'
    | '/parties'
    | '/reden'
    | '/votes'
    | '/members/$id/abstimmungen'
    | '/members/$id/anfragen'
    | '/members/$id/reden'
    | '/parties/$id/abstimmungen'
    | '/parties/$id/profil'
    | '/parties/$id/verlauf'
    | '/members/$id'
    | '/parties/$id'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/members/$id'
    | '/parties/$id'
    | '/votes/$id'
    | '/members/'
    | '/parties/'
    | '/reden/'
    | '/votes/'
    | '/members/$id/abstimmungen'
    | '/members/$id/anfragen'
    | '/members/$id/reden'
    | '/parties/$id/abstimmungen'
    | '/parties/$id/profil'
    | '/parties/$id/verlauf'
    | '/members/$id/'
    | '/parties/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  MembersIdRouteRoute: typeof MembersIdRouteRouteWithChildren
  PartiesIdRouteRoute: typeof PartiesIdRouteRouteWithChildren
  VotesIdRoute: typeof VotesIdRoute
  MembersIndexRoute: typeof MembersIndexRoute
  PartiesIndexRoute: typeof PartiesIndexRoute
  RedenIndexRoute: typeof RedenIndexRoute
  VotesIndexRoute: typeof VotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/': {
      id: '/votes/'
      path: '/votes'
      fullPath: '/votes/'
      preLoaderRoute: typeof VotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reden/': {
      id: '/reden/'
      path: '/reden'
      fullPath: '/reden/'
      preLoaderRoute: typeof RedenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/': {
      id: '/parties/'
      path: '/parties'
      fullPath: '/parties/'
      preLoaderRoute: typeof PartiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/votes/$id': {
      id: '/votes/$id'
      path: '/votes/$id'
      fullPath: '/votes/$id'
      preLoaderRoute: typeof VotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id': {
      id: '/parties/$id'
      path: '/parties/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof PartiesIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/$id': {
      id: '/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof MembersIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties/$id/': {
      id: '/parties/$id/'
      path: '/'
      fullPath: '/parties/$id/'
      preLoaderRoute: typeof PartiesIdIndexRouteImport
      parentRoute: typeof PartiesIdRouteRoute
    }
    '/members/$id/': {
      id: '/members/$id/'
      path: '/'
      fullPath: '/members/$id/'
      preLoaderRoute: typeof MembersIdIndexRouteImport
      parentRoute: typeof MembersIdRouteRoute
    }
    '/parties/$id/verlauf': {
      id: '/parties/$id/verlauf'
      path: '/verlauf'
      fullPath: '/parties/$id/verlauf'
      preLoaderRoute: typeof PartiesIdVerlaufRouteImport
      parentRoute: typeof PartiesIdRouteRoute
    }
    '/parties/$id/profil': {
      id: '/parties/$id/profil'
      path: '/profil'
      fullPath: '/parties/$id/profil'
      preLoaderRoute: typeof PartiesIdProfilRouteImport
      parentRoute: typeof PartiesIdRouteRoute
    }
    '/parties/$id/abstimmungen': {
      id: '/parties/$id/abstimmungen'
      path: '/abstimmungen'
      fullPath: '/parties/$id/abstimmungen'
      preLoaderRoute: typeof PartiesIdAbstimmungenRouteImport
      parentRoute: typeof PartiesIdRouteRoute
    }
    '/members/$id/reden': {
      id: '/members/$id/reden'
      path: '/reden'
      fullPath: '/members/$id/reden'
      preLoaderRoute: typeof MembersIdRedenRouteImport
      parentRoute: typeof MembersIdRouteRoute
    }
    '/members/$id/anfragen': {
      id: '/members/$id/anfragen'
      path: '/anfragen'
      fullPath: '/members/$id/anfragen'
      preLoaderRoute: typeof MembersIdAnfragenRouteImport
      parentRoute: typeof MembersIdRouteRoute
    }
    '/members/$id/abstimmungen': {
      id: '/members/$id/abstimmungen'
      path: '/abstimmungen'
      fullPath: '/members/$id/abstimmungen'
      preLoaderRoute: typeof MembersIdAbstimmungenRouteImport
      parentRoute: typeof MembersIdRouteRoute
    }
  }
}

interface MembersIdRouteRouteChildren {
  MembersIdAbstimmungenRoute: typeof MembersIdAbstimmungenRoute
  MembersIdAnfragenRoute: typeof MembersIdAnfragenRoute
  MembersIdRedenRoute: typeof MembersIdRedenRoute
  MembersIdIndexRoute: typeof MembersIdIndexRoute
}

const MembersIdRouteRouteChildren: MembersIdRouteRouteChildren = {
  MembersIdAbstimmungenRoute: MembersIdAbstimmungenRoute,
  MembersIdAnfragenRoute: MembersIdAnfragenRoute,
  MembersIdRedenRoute: MembersIdRedenRoute,
  MembersIdIndexRoute: MembersIdIndexRoute,
}

const MembersIdRouteRouteWithChildren = MembersIdRouteRoute._addFileChildren(
  MembersIdRouteRouteChildren,
)

interface PartiesIdRouteRouteChildren {
  PartiesIdAbstimmungenRoute: typeof PartiesIdAbstimmungenRoute
  PartiesIdProfilRoute: typeof PartiesIdProfilRoute
  PartiesIdVerlaufRoute: typeof PartiesIdVerlaufRoute
  PartiesIdIndexRoute: typeof PartiesIdIndexRoute
}

const PartiesIdRouteRouteChildren: PartiesIdRouteRouteChildren = {
  PartiesIdAbstimmungenRoute: PartiesIdAbstimmungenRoute,
  PartiesIdProfilRoute: PartiesIdProfilRoute,
  PartiesIdVerlaufRoute: PartiesIdVerlaufRoute,
  PartiesIdIndexRoute: PartiesIdIndexRoute,
}

const PartiesIdRouteRouteWithChildren = PartiesIdRouteRoute._addFileChildren(
  PartiesIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  MembersIdRouteRoute: MembersIdRouteRouteWithChildren,
  PartiesIdRouteRoute: PartiesIdRouteRouteWithChildren,
  VotesIdRoute: VotesIdRoute,
  MembersIndexRoute: MembersIndexRoute,
  PartiesIndexRoute: PartiesIndexRoute,
  RedenIndexRoute: RedenIndexRoute,
  VotesIndexRoute: VotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
